[google_oauth]
client_id = "814767699432-5mg8u4q7hnjlsgp2r500e8ani3cqqcqe.apps.googleusercontent.com"
client_secret = "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"
redirect_uri = "https://palm-oil-detector-vyvxsng9cvynfdydmmpgfd.streamlit.app/"


[app]
BACKEND_URL = "https://palm-oil-detector.onrender.com"